### ISSUE TITLE
Wotlk casters not fighting

### ISSUE THREAD

**Issue by Day3651** [celguar/mangosbot-bots#106]
Wotlk: Casters excluding healers won't cast. Druids won't use shapeshift forms. Reset bots and ai multiple times. in game message is attack target failed.

**Comment by wuyou17** [comment]
If you are not using an English client like me, then my method may be effective. 

Check spell.dbc in your dbc folder. The data in the file must be in English. You need data extracted from English client to replace dbc folder. Because robots can only recognize English names.

Good luck

**Comment by celguar** [comment]
Should be fixed
