### ISSUE TITLE
Herbs and Ore spawns

### ISSUE THREAD

**Issue by gsrour** [celguar/mangosbot-bots#11]
is there a reason why Herbs are all over the maps, i dont believe thats how it suppose to be. in westfall for instance, there are hundreds of herbs right next to each others including Earthroot where Earthroot are not suppose to be spawned there.

**Comment by celguar** [comment]
Thanks for report, @gsrour !
Earthroot [should be spawned](https://classic.wowhead.com/object=1619/earthroot) in Westfall!
I'll check the spawn quantity! Feel free to report any other overgrown herbs! 👍

**Comment by gsrour** [comment]
Hey Man and thank you for your fast reply!
Just use .gm fly on, and fly over westfall and other areas, while you have find herbs On, and see for yourself.
Thx
Gus.

Sent from Mail for Windows 10
