### ISSUE TITLE
BOT LOGICS

### ISSUE THREAD

**Issue by atidot3** [celguar/mangosbot-bots#110]
Hi,

It looks like bot doesnt do anything from their battle strategy.

No attack at all from ranged.
Only auto attack from melee.

They seems to be using potion and ask for heal when low but that's all.
They also look pretty AFK most of them stand still even with 100% bot active on settings.

**Comment by celguar** [comment]
I'm sorry but I need more details, expansion, classes etc. I don't see these problems in my setup atm

**Comment by atidot3** [comment]
Aight sorry sould have specified,

Core: mangos-one last rev
Module: mangosbot-bots last rev
Expansion: TBC

Class: all they just auto attack and never cast any spell.

My config file:
`##########################################
# MANGOS Ai Playerbot Configuration file #
##########################################

[AiPlayerbotConf]
ConfVersion=2020072501

# Enable or disable AI Playerbot
AiPlayerbot.Enabled = 1

# Enable random bot system
AiPlayerbot.RandomBotAutologin = 1

# Log on all random bots on start
AiPlayerbot.RandomBotLoginAtStartup = 1

# Delete all random bot accounts (reset randombots)
AiPlayerbot.DeleteRandomBotAccounts = 0

# auto-login all player alts as bots on player login
AiPlayerbot.BotAutologin = 0

# Guild Task system
AiPlayerbot.EnableGuildTasks = 0

# Enable LFG for random bots (NYI)
AiPlayerbot.RandomBotJoinLfg = 1

# Enable BG/Arena for random Bots
AiPlayerbot.RandomBotJoinBG = 1

# Enable Auto join BG - bots randomly join WSG and 2v2 Arena if server is not lagging
AiPlayerbot.RandomBotAutoJoinBG = 1

# Mark many quests <= Bot level as complete (slows down bot creation)
AiPlayerbot.PreQuests = 0

# Create random bot characters automatically
AiPlayerbot.RandomBotAutoCreate = 1

# Random bot count
AiPlayerbot.MinRandomBots = 100
AiPlayerbot.MaxRandomBots = 100
AiPlayerbot.RandomBotMinLevel = 1
AiPlayerbot.RandomBotMaxLevel = 60

# Accounts to create for random bots
AiPlayerbot.RandomBotAccountPrefix = rndbot
AiPlayerbot.RandomBotAccountCount = 200

# Percentage of fully active bots. Default is 10, higher numbers may affect performance
AiPlayerbot.botActiveAlone = 100

# Random bot guild count
AiPlayerbot.RandomBotGuildCount = 20

# Delete all random bot guilds
AiPlayerbot.DeleteRandomBotGuilds = 0

# Random bot arena team count
AiPlayerbot.RandomBotArenaTeamCount = 20

# Delete all random bot arena teams
AiPlayerbot.DeleteRandomBotArenaTeams = 0

# Maps to teleport random bots
AiPlayerbot.RandomBotMaps = 0,1,530,571

# Change random bot has lower gear
AiPlayerbot.RandomGearLoweringChance = 0.15

# Chance random bot has max level on first randomize (default 0.15)
AiPlayerbot.RandomBotMaxLevelChance = 0.15

# Chance bot chooses RPG (Teleport to random camp for their level) instead of grinding
AiPlayerbot.RandomBotRpgChance = 0.20

# Show progress bars for random bots (disabled by default)
AiPlayerbot.ShowProgressBars = 1

# Set randombots movement speed to walking anywhere
AiPlayerbot.RandombotsWalkingRPG = 0

# Set randombots movement speed to walking only inside buildings
AiPlayerbot.RandombotsWalkingRPG.InDoors = 0

# Bots greet to the players
AiPlayerbot.EnableGreet = 0

# Show helmet and cloak on randombots (reset required)
AiPlayerbot.RandomBotShowHelmet = 1
AiPlayerbot.RandomBotShowCloak = 1

# Disable random levels for randombots
# Every bots started on the specified level and level up by killing mobs.
AiPlayerbot.DisableRandomLevels = 0

# Set randombots starting level here if "AiPlayerbot.DisableRandomLevels" enabled
# Recommended: 5+
#AiPlayerbot.randombotStartingLevel = 5

# Set kill XP rate for bots (default: 10) (NYI)
# Server XP Rate * AiPlayerbot.KillXPRate
#AiPlayerbot.KillXPRate = 10

# Set minimum level of randombots where gets enchants on items (Maxlevel + 1 to disable)
# Default: 60
AiPlayerbot.minEnchantingBotLevel = 60

# Randombots checking players gear score level and deny the group invite if it's too low
# Default: 1 (enabled)
AiPlayerbot.GearScoreCheck = 0

# Quest that will be completed and rewarded to all random bots
AiPlayerbot.RandomBotQuestIds = 7848,3802,5505,6502,7761

# Randombots will group with nearby bots to do shared quests
AiPlayerbot.RandomBotGroupNearby = 1

# Bots without a master will say their lines
# AiPlayerbot.RandomBotSayWithoutMaster = 0

# Automation

# Bots pick their quest reward (yes = picks first useful item, no = list all rewards, ask = pick useful item and lists if multiple)
AiPlayerbot.AutoPickReward = yes

# Bots equip upgrades (Bots will equip any item obtained from looting or a quest if they are upgrades)
# Default: 0 (disabled)
AiPlayerbot.AutoEquipUpgradeLoot = 1

# Sync quests with player (Bots will complete quests the moment you hand them in. Bots will ignore looting quest items.)
# Default: 0 (disabled)
AiPlayerbot.SyncQuestWithPlayer = 0

# Bot automatically trains spells when talking to trainer (yes = train all available spells as long as the bot has the money, free = auto trains with no money cost, no = only list spells)
AiPlayerbot.AutoTrainSpells = yes

# Bot automatically picks talent points based on current spec (full = pick spec based on probability if multiple are like current spec, semi = only apply points if 1 spec looks like current spec, no = no auto talent points)
AiPlayerbot.AutoPickTalents = full

# Bots automatically learn trainable spells on levelup
# Default: 0 (disabled)
AiPlayerbot.AutoLearnTrainerSpells = 0

# Bots automatically learn classquest reward spells on levelup
# Default: 0 (disabled)
AiPlayerbot.AutoLearnQuestSpells = 0

# Random Bots will pick quests on their own and try to complete
# Default: 0 (disabled)
AiPlayerbot.AutoDoQuests = 0

##################################################################################
#                                                                                #
# All other parameters are optional but can be changed by uncommenting them here #
#                                                                                #
##################################################################################

##################################################################################
#                                                                                #
# Premade builds                                                                 #
#                                                                                #
##################################################################################
#
# AiPlayerbot.PremadeSpecName.<class>.<specno> = <name>         #Name of the talent specialisation
# AiPlayerbot.PremadeSpecProb.<class>.<specno> = <number>       #Probability Randombots will pick this spec. (default 100)
# AiPlayerbot.PremadeSpecLink.<class>.<specno>.<level> = <link> #Wowhead style link the bot should work towards at given level.

#
# Rogue example
# Assassination example

AiPlayerbot.PremadeSpecName.4.0 = pve dps assasination
AiPlayerbot.PremadeSpecProb.4.0 = 100
AiPlayerbot.PremadeSpecLink.4.0.30 = 005302105041                    # Work towards Cold Blood
AiPlayerbot.PremadeSpecLink.4.0.52 = 00532310505105-3203-05          # Unlock Seal Fate, Imp backstab and then take opportunity
AiPlayerbot.PremadeSpecLink.4.0.60 = 00532310505105-320305002001-05  # Final spec

# Combat example

AiPlayerbot.PremadeSpecName.4.1 = pve dps combat
AiPlayerbot.PremadeSpecProb.4.1 = 100
AiPlayerbot.PremadeSpecLink.4.1.20 = -02305001                       # Improved SS first, then unlock riposte. This is to avoid points in precicison before riposte.
AiPlayerbot.PremadeSpecLink.4.1.30 = -02305501000401                 # Unlock bladeflury first
AiPlayerbot.PremadeSpecLink.4.1.56 = 005302105-0230550100040140231   # Unlock Adrenaline rush and then relentles strikes after that it goes to lethality
AiPlayerbot.PremadeSpecLink.4.1.60 = 00530310503-0230550100050130231 # Final spec. From 56 it will pick up the last point in imp snd and finish with imp poisons.

# Preset talents supplied by Lidocain. Do you have more/improved specs? Let us know!

# Warrior
AiPlayerbot.PremadeSpecName.1.0 = pve arms
AiPlayerbot.PremadeSpecLink.1.0.60 = 303050213520105001-0505300502
AiPlayerbot.PremadeSpecName.1.1 = pve fury
AiPlayerbot.PremadeSpecLink.1.1.60 = 30305001302-05050005525010051
AiPlayerbot.PremadeSpecName.1.2 = pve prot
AiPlayerbot.PremadeSpecLink.1.2.60 = 05005001-05-55250110530101051

AiPlayerbot.PremadeSpecName.1.3 = pvp arms
AiPlayerbot.PremadeSpecLink.1.3.60 = 023050213320105031-55000131005
AiPlayerbot.PremadeSpecName.1.4 = pvp fury
AiPlayerbot.PremadeSpecLink.1.4.60 = 30325001302-05052130025012051
AiPlayerbot.PremadeSpecName.1.5 = pvp prot
AiPlayerbot.PremadeSpecLink.1.5.60 = 05003--55255113032021251

# Paladin
AiPlayerbot.PremadeSpecName.2.0 = pve dps ret (basic ret)
AiPlayerbot.PremadeSpecLink.2.0.60 = 550001-503-542300512003151
AiPlayerbot.PremadeSpecName.2.1 = pve dps ret (geared ret)
AiPlayerbot.PremadeSpecLink.2.1.60 = 5550012--552300512003151
AiPlayerbot.PremadeSpecName.2.2 = pve heal holy (sanctuary)
AiPlayerbot.PremadeSpecLink.2.2.60 = 0550312152105-503251000131
AiPlayerbot.PremadeSpecName.2.3 = pve heal holy (prot! holy shock taunt)
AiPlayerbot.PremadeSpecLink.2.3.60 = 55153122501001-053200334

AiPlayerbot.PremadeSpecName.2.4 = pvp heal holy
AiPlayerbot.PremadeSpecProb.2.4 = 80
AiPlayerbot.PremadeSpecLink.2.4.60 = 05503120521351-05025033
AiPlayerbot.PremadeSpecName.2.5 = pvp heal Holy
AiPlayerbot.PremadeSpecProb.2.5 = 80
AiPlayerbot.PremadeSpecLink.2.5.60 = 05503112521051-05324100032
AiPlayerbot.PremadeSpecName.2.6 = pvp tank prot
AiPlayerbot.PremadeSpecProb.2.6 = 80
AiPlayerbot.PremadeSpecLink.2.6.60 = 500501-053050335001051-05004
AiPlayerbot.PremadeSpecName.2.7 = pvp dps ret
AiPlayerbot.PremadeSpecProb.2.7 = 80
AiPlayerbot.PremadeSpecLink.2.7.60 = 505001-0531-502310512203151
AiPlayerbot.PremadeSpecName.2.8 = pvp dps ret (Loaded Reck Bomb)
AiPlayerbot.PremadeSpecProb.2.8 = 80
AiPlayerbot.PremadeSpecLink.2.8.60 = -0532010153005-50203151220311

# Hunter
AiPlayerbot.PremadeSpecName.3.0 = pve dps mm (mm/sv)
AiPlayerbot.PremadeSpecProb.3.0 = 60
AiPlayerbot.PremadeSpecLink.3.0.60 = 2-05251030513051-33202004103
AiPlayerbot.PremadeSpecName.3.1 = pve dps mm (mm/bm)
AiPlayerbot.PremadeSpecProb.3.1 = 60
AiPlayerbot.PremadeSpecLink.3.1.60 = 55000000505-05251030513051
AiPlayerbot.PremadeSpecName.3.2 = pve dps mm (mm/sv)
AiPlayerbot.PremadeSpecProb.3.2 = 60
AiPlayerbot.PremadeSpecLink.3.2.60 = 5-05351030503051-33050022
AiPlayerbot.PremadeSpecName.3.3 = pve dps bm (farmer)
AiPlayerbot.PremadeSpecProb.3.3 = 60
AiPlayerbot.PremadeSpecLink.3.3.60 = 5000322050521231-054510005
AiPlayerbot.PremadeSpecName.3.4 = pve dps mm
AiPlayerbot.PremadeSpecProb.3.4 = 60
AiPlayerbot.PremadeSpecLink.3.4.60 = 53000200505-05351030503051

AiPlayerbot.PremadeSpecName.3.5 = pvp dps surv
AiPlayerbot.PremadeSpecLink.3.5.60 = -5105103051-330005241030315
AiPlayerbot.PremadeSpecName.3.6 = pvp dps mm
AiPlayerbot.PremadeSpecLink.3.6.60 = -52051030513051-03222304103
AiPlayerbot.PremadeSpecName.3.7 = pvp dps bm
AiPlayerbot.PremadeSpecLink.3.7.60 = 1500322150501051-051510305

# Rogue
AiPlayerbot.PremadeSpecName.4.2 = pve dps combat (swords)
AiPlayerbot.PremadeSpecLink.4.2.60 = 005323105-3210052020050150231
AiPlayerbot.PremadeSpecName.4.3 = pve dps combat (daggers)
AiPlayerbot.PremadeSpecLink.4.3.60 = 005023005-3203052020550100201-05
AiPlayerbot.PremadeSpecName.4.4 = pve dps combat (daggers2)
AiPlayerbot.PremadeSpecLink.4.4.60 = 305020005-02505501005001-50005002
AiPlayerbot.PremadeSpecName.4.5 = pve dps combat
AiPlayerbot.PremadeSpecLink.4.5.60 = 305023005-3200550100050150231

AiPlayerbot.PremadeSpecName.4.6 = pvp dps combat (swords)
AiPlayerbot.PremadeSpecLink.4.6.60 = 005323105-3210052020050150231
AiPlayerbot.PremadeSpecName.4.7 = pvp dps combat (daggers)
AiPlayerbot.PremadeSpecLink.4.7.60 = 005023005-3203052020550100201-05
AiPlayerbot.PremadeSpecName.4.8 = pvp dps combat (daggers2)
AiPlayerbot.PremadeSpecLink.4.8.60 = 305020005-02505501005001-50005002
AiPlayerbot.PremadeSpecName.4.9 = pvp dps combat
AiPlayerbot.PremadeSpecLink.4.9.60 = 305023005-3200550100050150231


# Priest
AiPlayerbot.PremadeSpecName.5.0 = pve heal disc
AiPlayerbot.PremadeSpecLink.5.0.60 = 505230130505101-0250510313
AiPlayerbot.PremadeSpecName.5.1 = pve heal holy
AiPlayerbot.PremadeSpecLink.5.1.60 = 5012301305001-025051031300055
AiPlayerbot.PremadeSpecName.5.2 = pve dps shadow
AiPlayerbot.PremadeSpecLink.5.2.60 = 50520013--5032504103501051

AiPlayerbot.PremadeSpecName.5.3 = pvp dps disc
AiPlayerbot.PremadeSpecLink.5.3.60 = 500232130225151-20525100202
AiPlayerbot.PremadeSpecName.5.4 = pvp heal holy
AiPlayerbot.PremadeSpecLink.5.4.60 = 5002321331-2250511323001051
AiPlayerbot.PremadeSpecName.5.5 = pvp dps shadow
AiPlayerbot.PremadeSpecLink.5.5.60 = 50023212032--0502322103511051

# Shaman
AiPlayerbot.PremadeSpecName.7.0 = pve dps elem (elemental mastery)
AiPlayerbot.PremadeSpecLink.7.0.60 = 550331050002151--05204301005
AiPlayerbot.PremadeSpecName.7.1 = pve dps elem (nature's swiftness)
AiPlayerbot.PremadeSpecLink.7.1.60 = 55030105030215--0520430100501
AiPlayerbot.PremadeSpecName.7.2 = pve dps elem (force of nature + hand of edward the odd)
AiPlayerbot.PremadeSpecLink.7.2.60 = 5500315023101--0500535100501
AiPlayerbot.PremadeSpecName.7.3 = pve heal resto (pure)
AiPlayerbot.PremadeSpecLink.7.3.60 = -5-550350512553151
AiPlayerbot.PremadeSpecName.7.4 = pve heal resto (melee support resto)
AiPlayerbot.PremadeSpecLink.7.4.60 = -5120202-550350510503151

AiPlayerbot.PremadeSpecName.7.5 = pvp dps elem (nature's swiftness)
AiPlayerbot.PremadeSpecLink.7.5.60 = 55010105230215--0500531100501
AiPlayerbot.PremadeSpecName.7.6 = pvp dps elem (elemental mastery)
AiPlayerbot.PremadeSpecLink.7.6.60 = 550101052302151--05005311005
AiPlayerbot.PremadeSpecName.7.7 = pvp dps elem (elemental mastery)
AiPlayerbot.PremadeSpecLink.7.7.60 = 55000135030215--0523031100501
AiPlayerbot.PremadeSpecName.7.8 = pvp dps enhan (2hand)
AiPlayerbot.PremadeSpecLink.7.8.60 = 0523015003-5025230104003151
AiPlayerbot.PremadeSpecName.7.9 = pvp heal resto
AiPlayerbot.PremadeSpecLink.7.9.60 = -5-550350512553151

# Mage
AiPlayerbot.PremadeSpecName.8.0 = pve dps arcane
AiPlayerbot.PremadeSpecProb.8.0 = 33
AiPlayerbot.PremadeSpecLink.8.0.60 = 2300450310031531--053500030013
AiPlayerbot.PremadeSpecName.8.1 = pve dps fire
AiPlayerbot.PremadeSpecProb.8.1 = 33
AiPlayerbot.PremadeSpecLink.8.1.60 = 23005500002-5052020023033051-003
AiPlayerbot.PremadeSpecName.8.2 = pve dps frost (winter’s chill spec)
AiPlayerbot.PremadeSpecProb.8.2 = 33
AiPlayerbot.PremadeSpecLink.8.2.60 = 230045030003--05350003101301351
AiPlayerbot.PremadeSpecName.8.3 = pve dps frost (frost build for farming)
AiPlayerbot.PremadeSpecProb.8.3 = 33
AiPlayerbot.PremadeSpecLink.8.3.60 = -055002302003-24250230102051301
AiPlayerbot.PremadeSpecName.8.4 = pve dps frost (frost-arcane)
AiPlayerbot.PremadeSpecProb.8.4 = 33
AiPlayerbot.PremadeSpecLink.8.4.60 = 250005030011--05050203132351301
AiPlayerbot.PremadeSpecName.8.5 = pve dps frost (fun)
AiPlayerbot.PremadeSpecProb.8.5 = 33
AiPlayerbot.PremadeSpecLink.8.5.60 = 230005--05353203101351351
AiPlayerbot.PremadeSpecName.8.6 = pve dps frost (aoe farm)
AiPlayerbot.PremadeSpecProb.8.6 = 33
AiPlayerbot.PremadeSpecLink.8.6.60 = 230055001003--25300233132301301
AiPlayerbot.PremadeSpecName.8.7 = pve dps arcane (glass cannon)
AiPlayerbot.PremadeSpecProb.8.7 = 33
AiPlayerbot.PremadeSpecLink.8.7.60 = 2300550310031531--053500030003
AiPlayerbot.PremadeSpecName.8.8 = pve dps frost
AiPlayerbot.PremadeSpecProb.8.8 = 33
AiPlayerbot.PremadeSpecLink.8.8.60 = 230045200003--05050033132301051

AiPlayerbot.PremadeSpecName.8.9 = pvp dps frost
AiPlayerbot.PremadeSpecLink.8.9.60 = 20500322102--05053203102351301
AiPlayerbot.PremadeSpecName.8.10 = pvp dps frost (frosted fun)
AiPlayerbot.PremadeSpecLink.8.10.60 = 230005001--05350233132351301
AiPlayerbot.PremadeSpecName.8.11 = pvp dps arcane (venruki)
AiPlayerbot.PremadeSpecLink.8.11.60 = 2300512312201531-05523201-002

# Warlock
AiPlayerbot.PremadeSpecName.9.0 = pve dps demo (ds/ruin)
AiPlayerbot.PremadeSpecLink.9.0.60 = 25002-205030015221-52500051020001
AiPlayerbot.PremadeSpecName.9.1 = pve dps demo (succubus sacrifice)
AiPlayerbot.PremadeSpecLink.9.1.60 = 25002-2050300142301-52500051020001
AiPlayerbot.PremadeSpecName.9.2 = pve dps dest (imp lord)
AiPlayerbot.PremadeSpecLink.9.2.60 = 05002-2350300142001-52500051220001
AiPlayerbot.PremadeSpecName.9.3 = pve dps demo (sm/ruin)
AiPlayerbot.PremadeSpecLink.9.3.60 = 5502203112201105--50502051020001
AiPlayerbot.PremadeSpecName.9.4 = pve dps affli
AiPlayerbot.PremadeSpecLink.9.4.60 = 55002530122010051-2351050102

AiPlayerbot.PremadeSpecName.9.5 = pvp dps demo (sl)
AiPlayerbot.PremadeSpecProb.9.5 = 71
AiPlayerbot.PremadeSpecLink.9.5.60 = 05002-20503011525010512-05500001
AiPlayerbot.PremadeSpecName.9.6 = pvp dps demo (soul link/ shadowburn)
AiPlayerbot.PremadeSpecProb.9.6 = 71
AiPlayerbot.PremadeSpecLink.9.6.60 = 35-2050310152501051-50500011
AiPlayerbot.PremadeSpecName.9.7 = pvp dps demo (soul link/ nightfall)
AiPlayerbot.PremadeSpecProb.9.7 = 71
AiPlayerbot.PremadeSpecLink.9.7.60 = 35000232122-2050310152501051
AiPlayerbot.PremadeSpecName.9.8 = pvp dps affli (sm/ruin)
AiPlayerbot.PremadeSpecProb.9.8 = 71
AiPlayerbot.PremadeSpecLink.9.8.60 = 2500213212201135--50500051022001
AiPlayerbot.PremadeSpecName.9.9 = pvp dps affli (drakedog)
AiPlayerbot.PremadeSpecProb.9.9 = 71
AiPlayerbot.PremadeSpecLink.9.9.60 = 05002-205-0555005102205151
AiPlayerbot.PremadeSpecName.9.10 = pvp dps affli (sm/ruin)
AiPlayerbot.PremadeSpecProb.9.10 = 71
AiPlayerbot.PremadeSpecLink.9.10.60 = 3500023212201135--50520051020001
AiPlayerbot.PremadeSpecName.9.11 = pvp dps destro (conflagrate)
AiPlayerbot.PremadeSpecProb.9.11 = 71
AiPlayerbot.PremadeSpecLink.9.11.60 = 35000231122-001-5052005102005141

# Druid
AiPlayerbot.PremadeSpecName.11.0 = pve dps feral
AiPlayerbot.PremadeSpecLink.11.0.60 = 014005301-5500021323202151-05
AiPlayerbot.PremadeSpecName.11.1 = pve dps feral (dps/tank hybrid)
AiPlayerbot.PremadeSpecLink.11.1.60 = 014005001-5050301323222151-05
AiPlayerbot.PremadeSpecName.11.2 = pve dps resto (swiftmend spec)
AiPlayerbot.PremadeSpecLink.11.2.60 = 0143002002--505503105315051
AiPlayerbot.PremadeSpecName.11.3 = pve dps resto (regrowth spec bear aoe farm)
AiPlayerbot.PremadeSpecLink.11.3.60 = 4100053312011--50530310031405
AiPlayerbot.PremadeSpecName.11.4 = pve dps resto (resto-balance)
AiPlayerbot.PremadeSpecLink.11.4.60 = 01430433020013--505103105115

AiPlayerbot.PremadeSpecName.11.5 = pvp dps resto (swiftmend / feral charge)
AiPlayerbot.PremadeSpecLink.11.5.60 = 0140002-5002321-055103105315011
AiPlayerbot.PremadeSpecName.11.6 = pvp dps resto
AiPlayerbot.PremadeSpecLink.11.6.60 = 0140003-5000501-055103105315021
AiPlayerbot.PremadeSpecName.11.7 = pvp dps feral (heart of the wild / ns)
AiPlayerbot.PremadeSpecLink.11.7.60 = 01-500152130320214-05501310231
AiPlayerbot.PremadeSpecName.11.8 = pvp dps balance (moonfury)
AiPlayerbot.PremadeSpecLink.11.8.60 = 510050300250135--50502310401
AiPlayerbot.PremadeSpecName.11.9 = pvp dps balance (boomkin)
AiPlayerbot.PremadeSpecLink.11.9.60 = 0143503002551351--5005021


# Prefix for bot chat commands (e.g. follow, stay)
#AiPlayerbot.CommandPrefix =

# Max AI iterations per tick
#AiPlayerbot.IterationsPerTick = 100

# Allow/deny bots from your guild
AiPlayerbot.AllowGuildBots = 1

# Delay between two short-time spells cast (Default 500)
AiPlayerbot.GlobalCooldown = 500

# Max wait time when moving
#AiPlayerbot.MaxWaitForMove = 5000

# Delay between two bot actions (default 100)
AiPlayerbot.ReactDelay = 100

# Inactivity delay
AiPlayerbot.PassiveDelay = 10000

# Minimum delay between repeating actions (chat messages, emotes etc)
AiPlayerbot.RepeatDelay = 5000

AiPlayerbot.RpgDelay = 10000

AiPlayerbot.SitDelay = 20000

AiPlayerbot.LootDelayDelay = 1000

# Distances
AiPlayerbot.SightDistance = 60.0
AiPlayerbot.SpellDistance = 26.0
AiPlayerbot.ShootDistance = 26.0
#AiPlayerbot.ReactDistance = 150.0
#AiPlayerbot.GrindDistance = 75.0
#AiPlayerbot.LootDistance = 15.0
#AiPlayerbot.FleeDistance = 15.0
#AiPlayerbot.TooCloseDistance = 5.0
#AiPlayerbot.MeleeDistance = 1.5
#AiPlayerbot.FollowDistance = 1.5
#AiPlayerbot.WhisperDistance = 6000.0
#AiPlayerbot.ContactDistance = 0.5
#AiPlayerbot.AoeRadius = 10
AiPlayerbot.RpgDistance = 200

# Bot can flee for enemy
AiPlayerbot.FleeingEnabled = 1

# Health/Mana levels
#AiPlayerbot.CriticalHealth = 25
#AiPlayerbot.LowHealth = 45
#AiPlayerbot.MediumHealth = 65
#AiPlayerbot.AlmostFullHealth = 85
#AiPlayerbot.LowMana = 15
#AiPlayerbot.MediumMana = 40

# Random bot default strategies (applied after defaults)
#AiPlayerbot.RandomBotCombatStrategies = +dps,+dps assist,-threat
#AiPlayerbot.RandomBotNonCombatStrategies = +grind,+loot,+rpg,+custom::say
#AiPlayerbot.CombatStrategies = +custom::say
#AiPlayerbot.NonCombatStrategies = +custom::say,+return


# How often tasks are changed
#AiPlayerbot.MinGuildTaskChangeTime = 172800
#AiPlayerbot.MaxGuildTaskChangeTime = 432000
# Mail spam interval
#AiPlayerbot.MinGuildTaskAdvertisementTime = 300
#AiPlayerbot.MaxGuildTaskAdvertisementTime = 28800
# Delay before reward is sent
#AiPlayerbot.MinGuildTaskRewardTime = 300
#AiPlayerbot.MaxGuildTaskRewardTime = 3600

# Quest items to leave (do not destroy)
#AiPlayerbot.RandomBotQuestItems = 6948,5175,5176,5177,5178,16309,12382,13704,11000

# PvP Restricted Zones (bots don't pvp)
#AiPlayerbot.PvpProhibitedZoneIds = 2255,656,2361,2362,2363,976,35,2268,3425,392,541,1446,3828,3712,3738,3565,3539,3623,4152,3988,4658,4284,4418,4436,4275,4323

# Spells every random bot will learn on randomize (54197 - cold weather flying)
#AiPlayerbot.RandomBotSpellIds = 1

# Level diff between random bots and nearby creatures for random teleports
#AiPlayerbot.RandomBotTeleLevel = 3

#AiPlayerbot.OpenGoSpell = 6477

# Intervals
AiPlayerbot.RandomBotUpdateInterval = 60
AiPlayerbot.RandomBotCountChangeMinInterval = 1800
AiPlayerbot.RandomBotCountChangeMaxInterval = 7200
#AiPlayerbot.MinRandomBotInWorldTime = 3600
#AiPlayerbot.MaxRandomBotInWorldTime = 1209600
#AiPlayerbot.MinRandomBotRandomizeTime = 7200
#AiPlayerbot.MaxRandomRandomizeTime = 1209600
AiPlayerbot.RandomBotsPerInterval = 60
#AiPlayerbot.MinRandomBotsPriceChangeInterval = 7200
#AiPlayerbot.MaxRandomBotsPriceChangeInterval = 172800

# How far random bots are teleported after death
AiPlayerbot.RandomBotTeleportDistance = 100

# Debug switches
#AiPlayerbot.SpellDump = 0
#AiPlayerbot.LogInGroupOnly = 1
#AiPlayerbot.LogValuesPerTick = 0
#AiPlayerbot.RandomChangeMultiplier = 1

# Command server port, 0 - disabled
#AiPlayerbot.CommandServerPort = 8888

AiPlayerbot.PerfMonEnabled = 1
`

**Comment by celguar** [comment]
I'm sorry i won't read that config. I asked expansion classes, roles that dont work.

**Comment by celguar** [comment]
I use latest tbc repack 2.2.6 all classes work for me

**Comment by celguar** [comment]
And a scenario that makes them bot work. Like what do you do? I did raids, I did BG whole week and all of them do stuff. So I need some more info. If you set them to passive they won't work ofc. Do /p reset ai

**Comment by atidot3** [comment]
Well, 

My game version is TBC 2.4.3
My current server sources is:
https://github.com/cmangos/mangos-tbc master

All encounter was under 60 on classic area, from compiled source no repack.
Im not using PLAYERBOT but ike's =>
https://github.com/celguar/mangosbot-bots master

Human starting zone:
- Human Priest standing forever
- Human paladin in a group with human mage
    - paladin only auto attack.
    - mage stand back in cast distance but do never cast spell.
    - warlock standind still near mobs, stays in ranged even if the mob move.
Ashenval:
- Gnome warrior
   - Doing quest, walking around, auto attacking mob.
      - never never used skill.
      - I recorded the gnome attacking some mobs: https://www.youtube.com/watch?v=yjd2p_ANSm4
- Blasted land
   - Shaman getting hit by 2 mobs, standing still not even healing himself, not attacking.
   - Rogue auto attacking mob, walking around, never used skill, never used stealth.

**Comment by celguar** [comment]
Please invite these bots to your group and see if they behave the same. Paladin low level uses holy rotation, it doesnt attack in group.

**Comment by celguar** [comment]
Bots can stand afk if they wait for group or just decided to wait. Please invite all classes (since you say all are bugged) in your raid and go kill some mobs to see if they are not doing anything. Note that healer specced bots won't attack in group

**Comment by celguar** [comment]
Also I have no idea how did you manage to use default cmangos with my ike3 bots fork. I only work with my cmangos-tbc fork , branch is not master, but ike3-bots

**Comment by celguar** [comment]
Anyway thanks for the info ;) I'll check the starting areas, probably a regression after recent updates

**Comment by atidot3** [comment]
I did tried with party (low level party and 58+ party), the behavior is the same:

- Melee only auto attack
- Caster stay in skill range but never use it

About the master branch its my bad sorry miss copy past:
https://github.com/atidot3/mangos-tbc/commit/a025eade0ddb7c3c87619680ad2bb0cf60762808

Merge your branch into master wich may be the unexpected behavior.
I'll try with yours stock.

Will let u know.

**Comment by celguar** [comment]
Okay I'll try some group tonight

**Comment by atidot3** [comment]
Just tried a fresh install with your mangos-tbc/ike and mangosbot-bots/master.
Same behavior, no skills etc.

**Comment by atidot3** [comment]
To provide more informations i did activate the debug mode on the fresh compiled server source:
Heal:
![priest](https://user-images.githubusercontent.com/3525729/182381980-6fc215d6-d575-448a-898a-4db06a584b09.PNG)
Dps:
![mage](https://user-images.githubusercontent.com/3525729/182381989-b7a98f7b-cb58-4769-b7aa-d932892eb5de.PNG)

vs on the repack:
Heal:
![heal](https://user-images.githubusercontent.com/3525729/182384710-0e37f730-b626-4c7f-a0d8-fcb0e0eee059.PNG)
Dps:
![sham](https://user-images.githubusercontent.com/3525729/182384725-00cc0bc4-441c-4322-ab02-cfc17fe75494.PNG)

**Comment by atidot3** [comment]
Finally sorted out.

Quick explain : this is dumb.
Longer explain:

My local game file is in French, so my DBCs was all in frFR.
I had to debug the all process of the AI to find out on the check cast spell condition the Localisation was the issue as the server wasnt able to find the spell named 'name' in the DBCs storage.
So after updating my DBCs i finally got this working.

Sorry if you wasted your time doing research !

PS: i wouldnt mind doing a PR with a warning log in case the localisation is incorrect for futur simillar issues.

**Comment by mostlikely4r** [comment]
I'm curious. Is this a cmangos wide issue or just ike3bot?

**Comment by celguar** [comment]
If you use non English dbc server has no info about English spell names so bots can't find it by name. Same for .lookup spell command.
