### ISSUE TITLE
WOTLK Crashing Out

### ISSUE THREAD

**Issue by mriggins** [celguar/mangosbot-bots#114]
[6aa90f07_mangosd.exe_[14-8_14-36-25].txt](https://github.com/celguar/mangosbot-bots/files/9334830/6aa90f07_mangosd.exe_.14-8_14-36-25.txt)

Fresh Win10 install, fresh SPP WOTLK install. Fresh everytrhing. 24 gigs of ram.

Server will startup fine and runs for a while. Then mangosd crashes.

Mangosd will not startup again unless I run the repair database after crash. At that point, it will start again and then crash out after a while.

I've tried reducing randombots, etc. Same thing. 

Crash log attached.

**Comment by kadeshar** [comment]
"For a while" means 15 minutes or 15 hours?
"Number Of Processors: 2" in your case its physical or logical processors? 
If logical try increase available logical processors.

Also try updating to:
Revision: 137ffa396da78d9747a3549b685d2ebb7a1d8235
Build: 2022-08-22T00:49:33+03:00

**Comment by sadpiken** [comment]
did you fix the crashes ?
