### ISSUE TITLE
Missing dll after downloading vanilla expansion (spp-httpd)

### ISSUE THREAD

**Issue by maximechoulet** [celguar/mangosbot-bots#117]
I followed the guide step by step and after downloading the vanilla expansion files, I get errors about missing dlls for spp-httpd.exe:

- libcrypto-1_1.dll
- icuuc64.dll

However, the expansion menu (with "Start Servers") does show.
Did I miss some prerequisite ?

**Comment by korttwulfe** [comment]
I'm having the same problem.  Did you find a fix for this issue?

**Comment by maximechoulet** [comment]
Downloading the files from the internet and pasting them next to spp-htttpd.exe worked for me.
I had a similar issue with another exe file and other dll, same fix.
