### ISSUE TITLE
classiccharacters.custom_transmogrification doesn't exist

### ISSUE THREAD

**Issue by Will7029** [celguar/mangosbot-bots#119]
Hello!

After updating latest playerbots from here, server console starts to spam this about transmogrification even i don't have one.
I'm using classic version. (Not repack).

My first time posting issue in Github, hopefully i'm doing it right. :)

![kuva](https://user-images.githubusercontent.com/113094853/189069231-3970b075-6bdb-42ba-adfb-18509d73d305.png)

**Comment by celguar** [comment]
Hello, I'm sorry I forgot to upload it to core repo. Take it from here https://github.com/celguar/spp-classics-cmangos/blob/master/sql/vanilla/characters/transmog_characters.sql
