### ISSUE TITLE
Dungeon Finder not working WotLK

### ISSUE THREAD

**Issue by masterben42** [celguar/mangosbot-bots#120]
Things have been going smooth, but the dungeon finder doesn't work. Ill que and the "time in queue" shows < 1 minute. even with bots I've invited it doesn't pop or anything.

**Comment by kadeshar** [comment]
Your party must have 1 tank, 1 healer, 3 dps. Usually i check spec using mangosbot 

![image](https://user-images.githubusercontent.com/28183654/192134247-500f226d-74f3-4ae2-bf62-51abcae19d54.png)
![image](https://user-images.githubusercontent.com/28183654/192134258-f94a6b25-7b1f-4e0c-99b0-047085e1ba3e.png)
![image](https://user-images.githubusercontent.com/28183654/192134269-92e5c0ab-e070-40d1-9c48-cfdbfe485b55.png)

Example: inviting dps paladin doesnt fill healer or tank spot.
