### ISSUE TITLE
Crash - Access violation (PathFinder)

### ISSUE THREAD

**Issue by kadeshar** [celguar/mangosbot-bots#127]
Exception thrown at 0x00007FF735BB087A in mangosd.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

Here screen from debugging tool
![image](https://user-images.githubusercontent.com/28183654/193852050-587d0c23-0df4-4a3e-8526-6f9f909174bf.png)

Crash files:
https://drive.google.com/open?id=17s6kJJhkCfgLD-KKWcv_0GVsG0L7E8Kj&authuser=kadeshar%40gmail.com&usp=drive_fs
https://drive.google.com/open?id=17uBSEKA4Wyqb7rlsA2ZQeI-9fLrzT-OD&authuser=kadeshar%40gmail.com&usp=drive_fs

**Comment by mostlikely4r** [comment]
Possible fix: https://github.com/kadeshar/mangos-wotlk/pull/1/commits/5d8bb638a5493bdf044c1826cb80c4ff955c994b

**Comment by kadeshar** [comment]
Compiled. I will make few tests.

**Comment by kadeshar** [comment]
Modified code line generating next access violation error 
![image](https://user-images.githubusercontent.com/28183654/194332715-1d220f3e-b206-4319-abaa-89f98d64b6bd.png)
