### ISSUE TITLE
Not sure what is wrong exactly, maybe spells list?

### ISSUE THREAD

**Issue by conjections** [celguar/mangosbot-bots#129]
Just recently started playing SPP. Took me forever to get it running at all. I finally got the server to start up. But while the server is loading up there's a bunch of red text saying something like "error: spell not found in spellstore" or something like that.

**Comment by conjections** [comment]
Oh I forgot to mention I tried playing despite this error, and the game just bogs down to a crawl. NPC's/quest givers don't give the quest until like 5 mins after you talk with them. Triggering/activating quest items don't go through. like if you have a channeled item, it just channels for a few seconds and then ends with no effect.

**Comment by kadeshar** [comment]
You can ignore this error its normal...
Your SPP server is located on SSD disc?

**Comment by conjections** [comment]
Ended up just installing a different repack and I'm good now. Thanks for the reply :) and my installation was on an SSD, yeah.
