### ISSUE TITLE
Dungeons command stay bug

### ISSUE THREAD

**Issue by kadeshar** [celguar/mangosbot-bots#130]
In Razorfen Downs bots often dont listen "stay" command.  
Instead of that they running somewhere or using heartstone.
Its very annoying to not have basic control on them.

![obraz](https://user-images.githubusercontent.com/28183654/195950957-bb0c2ce4-e009-45e8-a256-ce7da102ca0b.png)

**Comment by kadeshar** [comment]
Same error in Scarlet Monastery - Cathedral
![obraz](https://user-images.githubusercontent.com/28183654/195989058-ffd9f85a-565a-4296-9796-422d85b9c32a.png)

**Comment by zulacha** [comment]
Make sure you're the group leader, otherwise they'll just go rogue in this way. Should one of them become group leader you'll sometimes just magically be granted group leader and other times you need to reform the group entirely.
