### ISSUE TITLE
mangosbot addon can't use

### ISSUE THREAD

**Issue by yyhhrr** [celguar/mangosbot-bots#170]
is this addon out of data?when you select a bot in a group,they used to pup up a ui,but they won't now

**Comment by mostlikely4r** [comment]
What version of the server and addon are you using? (Ie. where did you get them or what commit?)

**Comment by davidonete** [comment]
Try using this version: https://github.com/celguar/mangosbot-addon/tree/e122c43c45f1965754a1e1b243f31246afe27d70
The latest version is meant to be used on the next SPP release coming soon

**Comment by yyhhrr** [comment]
Very thankful to [davidonete](https://github.com/davidonete),I use latest core and addon,it works.is there a bot manual,about how to use the bot?

**Comment by mostlikely4r** [comment]
A rough manual can be found here: https://ike3.github.io/mangosbot-docs/
Latest functions have not been documented 'yet'.
