### ISSUE TITLE
Very Lag

### ISSUE THREAD

**Issue by Wolfjorge** [celguar/mangosbot-bots#176]
When I take quest or combat, the server have lag, for 5 seconds or more, any more have this situation?

**Comment by poogie** [comment]
If you are using Questie, try disabling it. It worked for me

**Comment by celguar** [comment]
What are your PC specs , please?

**Comment by Wolfjorge** [comment]
Windows 10
32GB RAM
I7 - 10700K
Nvidia RTX 3080Ti
Nvme 2TB 

I think, the lag is for the bot its in the same zone, for example Ironforge, etc.

**Comment by celguar** [comment]
Hello, server lag means you talk to quest giver and its menu appears not instant. Or if you cast an instant spell and its taking more than a second to cast. If you have low fps then it's normal for wow 1.12 to have low fps in crowded areas. If you game freezes it may be caused by some addon you use

**Comment by celguar** [comment]
If you have server lag then try using beta build option, it may improve performance
