### ISSUE TITLE
Random Bots level not work.

### ISSUE THREAD

**Issue by Wolfjorge** [celguar/mangosbot-bots#195]
Hi every one! Happy new year!

I have problem with any expansion (Classic, TBC, Wotlk) the random bots level not work, 

If I make any change Im reset the random bots always.

I configure this lines:

AiPlayerbot.RandomBotMinLevel = 10
AiPlayerbot.RandomBotMaxLevel = 70

But all bot have a level 10.

And I dont understand this paramaters:

Change random bot has lower gear 
AiPlayerbot.RandomGearLoweringChance = 0.15

Chance random bot has max level on first randomize (default 0.15)
AiPlayerbot.RandomBotMaxLevelChance = 0.70

I set 0.70 for 70% to lvl 70? or I configure 70 for 70%? Any configuration, 0.70 or 70, the bots have lvl 10....

I configurate this too

Disable random levels for randombots
Every bots started on the specified level and level up by killing mobs.
AiPlayerbot.DisableRandomLevels = 0 or 1, random bot have lvl 10.

Set randombots starting level here if "AiPlayerbot.DisableRandomLevels" enabled
Recommended: 5+
AiPlayerbot.randombotStartingLevel = 5 or 10 or 20, all bots have lvl 10.

I have this parameters in the server conf.

MaxPlayerLevel = 70
StartPlayerLevel = 10

If change StartPlayerLevel, for 20 or 50 or 70, and reset de bots, always the random bots start in the level for start players... If is 20, the bots 20, if is 70 bots 70.... 

Any can help me please?

Very thanks and have a nice day.

**Comment by celguar** [comment]
Hello
1) delete random bots
2)
AiPlayerbot.RandomBotMinLevel = 10
AiPlayerbot.RandomBotMaxLevel = 70
And this max level chance config to 0.70
3) start server

**Comment by celguar** [comment]
Hello
1) delete random bots
2)
Starting player level set back to 1
AiPlayerbot.RandomBotMinLevel = 10
AiPlayerbot.RandomBotMaxLevel = 70
And this max level chance config to 0.70
3) start server

**Comment by Wolfjorge** [comment]
Hi! thanks, I do it. You are the best!

Other question,

Change random bot has lower gear
AiPlayerbot.RandomGearLoweringChance = 0.15

If I wish all bots have a Great Gear for instances, raids, etc. How to configure?
