### ISSUE TITLE
Bots Stuck in Mount Loop [Beta]

### ISSUE THREAD

**Issue by Day36512** [celguar/mangosbot-bots#197]
I've noticed a number of bots summoning and dismissing their mounts in 1.12. They seem to get stuck in a loop like they're spamming the mount button. Paladins, I've also noticed, will try to mount when moving from point a to point b but fail. Might be an issue with other bots too.

**Comment by mostlikely4r** [comment]
This is a known issue but hard to reproduce. I'll see if I can find a good solution.
