### ISSUE TITLE
Is it possible to restrict lvl 60 playerbots to rare gear?

### ISSUE THREAD

**Issue by Alsoborte** [celguar/mangosbot-bots#200]
I have tried editing the equipment cache .sql file by deleting all the epic items, but they are still spawning with them. Am I editing the right file? 

Thanks in advance.

**Comment by mostlikely4r** [comment]
AiPlayerbot.RandomGearMaxLevel = 50
AiPlayerbot.RandomGearMaxDiff = 40

You can use these config lines. The first one limits the itemlevel of the gear bots can get on randomisation. The second is the itemlevel difference between the bot and the gear selected.

It's not exactly what you ask for but playing with the first value while keeping the second large should give some usefull results.

**Comment by celguar** [comment]
@Alsoborte did you delete bots after removing epic items from equip cache?

**Comment by Alsoborte** [comment]
@mostlikely4r that worked great! Thank you!

@celguar yes, I deleted all bots before restarting server. Should that have worked?
