### ISSUE TITLE
Bundled website not working

### ISSUE THREAD

**Issue by Griptor** [celguar/mangosbot-bots#201]
Hi all
I'm really enjoying SPP classics and I have the server running great.
I have installed the latest version and all updates from the WotLK version from Git Hub.
I have installed it on the server and changed the IP to 192.1.XXX so that other members of the house can connect. And now we can all play fine :)

The website works fine on my pc however...

The website no longer works on the server :( no armory or player maps etc
It won't launch the website with the "M" key on the official tool and I don't know how to change its IP to that of the server.
I'm also running a few other apps such as plex etc, but they all seem to be working fine so I don't think there is a port conflict.

Im sure its an ez fix

Any help would be greatly appreciated :)

**Comment by celguar** [comment]
Hello

in browser: http://192.1.X.X

**Comment by Griptor** [comment]
yeah i have tried that but didnt work

**Comment by celguar** [comment]
Does it work on host pc

**Comment by Griptor** [comment]
no :(
but it works on my desktop when I run the server app
before I changed the IP to connect to the other machine.
it's pretty weird I can reach the plex website and some other ones.

I don't know what port it is either as it connects automatically id assume port 80

**Comment by celguar** [comment]
So it never worked on this PC? What do you see when you try to connect? What error?

**Comment by Griptor** [comment]
just a cant connect blank page error

**Comment by Griptor** [comment]
i think if i changed the ip back to 127.0.0.1 it would work but then we couldnt connect lol

**Comment by celguar** [comment]
Did you create a second realm?

**Comment by Griptor** [comment]
no

**Comment by celguar** [comment]
So what error do you see? Is it error 500? If not, is web server even running? It should be a blank black console window. It starts when you select expansion

**Comment by Griptor** [comment]
This 127.0.0.1 page can’t be found
No webpage was found for the web address: http://127.0.0.1/
HTTP ERROR 404

**Comment by Griptor** [comment]
ima try a fresh install and see how its goes

**Comment by celguar** [comment]
What about my second question

**Comment by celguar** [comment]
Also you can try localhost instead of 127.0.0.1 in url

**Comment by Griptor** [comment]
I have just done a fresh install in a different folder, and updates and still no website...
no local host either so im guessing some other app maybe using the port?

**Comment by Griptor** [comment]
I have made a list of all the ports iv set up with the other apps that were running to see if there were any conflicts.

network IP
192.168.8.105

local
127.0.0.1

localhost:
ports

plex		32400
emby	8096

utorrent	8080
prowler	9696

radarr	7878   * changed to 8998
sonarr	8989
lidarr	8686
readarr	8787


wow stuff 
realmd
bindip	0.0.0.0
login db	3310
realm server port	3724

mangosd
LoginDatabaseInfo     3310
WorldDatabaseInfo     3310
CharacterDatabaseInfo 3310
LogsDatabaseInfo      3310
PlayerbotDatabaseInfo 3310
WorldServerPort = 8085
BindIP = "0.0.0.0"
SOAP.IP = 127.0.0.1
SOAP.Port = 7878 *
Ra.IP = 0.0.0.0
Ra.Port = 3443
Metric.Address = "127.0.0.1"
Metric.Port = 8086

SQL DB
wotlkrealmd		realmlist	adddress	127.0.0.1	   /data tab 127.0.0.1


I have changed one port however has not fixed the problem.
Even when other apps are not running website still doesn't load,
not even with a fresh install in a separate folder.

This is strange as I have only put a fresh install of win 11 on the server
a few weeks ago and everything is running quite smoothly.

**Comment by celguar** [comment]
You still didn't answer my question :p

**Comment by Griptor** [comment]
sorry
no it does not work on host pc

**Comment by Griptor** [comment]
i think i have located the problem
the apache server is not running on the host pc 
it runs on my pc but not the host
Thanks for your help 👍

**Comment by Griptor** [comment]
Turns out the server monitor is running but the httpd.exe and spp-httpd.exe refuse to run.
I have checked TCP port 80 and it is listening and not established.
Do you know how to fix apache?

**Comment by celguar** [comment]
No I don't. Make sure your windows has all vcredist packages for both x86 and x64, latest bet framework too

**Comment by celguar** [comment]
No I don't. Make sure your windows has all vcredist packages for both x86 and x64, latest bet framework too

Maybe apache has some logs, but I never messed with that, you'll have to look for them yourself
