### ISSUE TITLE
Druid bots spam bear form every second

### ISSUE THREAD

**Issue by westernoutlaw** [celguar/mangosbot-bots#204]
Hello, I'm using the latest stable version of SPP and I ran into an issue with druid bots which I can't seem to resolve.
When a druid starts combat it shifts into bear and all is fine, until it comes into contact with the target. When attacks something in bear form, it constantly casts bear form, running out of mana in seconds
I failed to understand the reason behind it, I tried changing bot's strategy in many ways, resetting ai to default, making new druids for testing, removing anything with casting, or racials, even leaving nothing but "bear" in "co", then it just stands there taking hits and shifting every second anyway
I also tried using BETA version and it's the same here

I'm using 3.3.5 version

**Comment by celguar** [comment]
Hello, there is an issue that makes druids come out of form to cast omen of clarity. We are working in a fix. Meanwhile you can make druid cast it before combat, by whispering "do omen of clarity". Then it should not try to cast it in combat (until it expires ofc)

**Comment by westernoutlaw** [comment]
I doubt that was the reson for it, my druid was level 12 with no talents on. It wasn't casting anything but Bear Form every second or so according to combat chat. It wasn't coming out of the bear, just casting it over and over until no mana is left. And it only did it when hitting the enemy/being hit
