### ISSUE TITLE
Mangosd infiniting loading, can't create account

### ISSUE THREAD

**Issue by SnarksOne** [celguar/mangosbot-bots#207]
RE: Starting server

- To start server, choose "Start Servers (Win64)" and wait for it to load.
- It will take longer to boot for the first time, because random bot characters will be created.
- To create an account, choose option in the menu and follow the instructions.
- To log in - edit realmlist.wtf file - "set realmlist 127.0.0.1"

Setup/Installs WoTLK module just fine, and server starts off fine.

However, after launching the 3 BAT files,  the mangosd.exe window never stops loading bot information?  Just runs infinitely. Not sure what i'm doing wrong..  I can't create an account in that window... Launching the 3.3.5a client doesn't show available server when set realmlist to 127.0.01.

**Comment by celguar** [comment]
Hello! What do you mean by 3 bat files. To start server you only need one

**Comment by celguar** [comment]
Also if you click in server console with mouse you can pause server. So don't click there. If you paused server hit enter to unpause. If you need further assistance please provide last log lines you see in "frozen" mangosd console

**Comment by SnarksOne** [comment]
Hi thx. I'm running the launcher.bat ( \SPP_Classics_V2\SPP_Server\Launcher.bat) to get to the menu where start launcher is listed.  Yes I found that out that clicking in window temporarily halts things, then starts it.  That's fine.

Server running maybe fine:  Not seeing "frozen" in the mangosd output window.  In fact it appears to be running, the problem is maybe I'm being too impatient with bots loading?   How long does that part take? I'm getting output that appears to be bot activity ongoing.  At some point, Mangosd window output shows this:

-----------------------------------------
CMANGOS World Initiated
Server start up time: 3min 47 sec
----------------------------------------

After that it's running an ongoing output which appears to be bot activity (x bot "sent to grind" etc...) Does this end, or what do i do next.  

Thanks again...

**Comment by celguar** [comment]
No clicking inside console is not temporary if you click inside it it will pause forever until you unpause it.

Server Initialized means server has started and you can play

**Comment by celguar** [comment]
Like, you type in that console (don't look at text coming and replacing, it will work)
acc cre login pass
(Login pass are your login and pass)
And hit enter

Then you go to your wow folder
wow 3.3.5/Data/enUS/realmlist.wtf, open with notepad and edit to
set realmlist 127.0.0.1

Then start wow and login

**Comment by SnarksOne** [comment]
Ok will do, looks great I can't wait to see this !

**Comment by celguar** [comment]
You already saw this 
Server start up time: 3min 47 sec

**Comment by celguar** [comment]
It means server has started and you can play

**Comment by SnarksOne** [comment]
Yep, everything is working great!  I'm in game playing.   

Didn't realize I had to create account (typed in mangosd window while it was running)  but no problems it worked as you said.

Thanks again!  this looks fantastic can't wait to dive in.

**Comment by celguar** [comment]
Btw if you see some instability like mangos crashing a lot try switching to beta build in launcher
