### ISSUE TITLE
Can't revive character

### ISSUE THREAD

**Issue by yyhhrr** [celguar/mangosbot-bots#211]
use latest beta version

**Comment by celguar** [comment]
Hello, any detail?

**Comment by yyhhrr** [comment]
I see you update core .But i don't select hardcore mod.It seems like the hardcore mod be used by default.

**Comment by yyhhrr** [comment]
/g .revive no effect.Your character still dead.

**Comment by celguar** [comment]
Thanks we'll fix it asap

**Comment by celguar** [comment]
Hello, try update beta build

**Comment by yyhhrr** [comment]
It works
