### ISSUE TITLE
(WOTLK Beta) Summon command

### ISSUE THREAD

**Issue by BloodRunsCold** [celguar/mangosbot-bots#212]
Hey, is there a way to revert the "summon" command back to how it used to be in the previous versions of the beta? it currently either teleports me to one of the bots, or the bots tell me that there are no meeting stones or innkeepers nearby. As great as the bots are, they still get stuck sometimes, and it's also just convenient being able to summon your whole party to your location, or to the entrance of a dungeon without the need for a meeting stone. Could there at least be an option to toggle between the new and old version of the command? thank you for your work and the repack!

**Comment by celguar** [comment]
.summon is a gm command

**Comment by celguar** [comment]
Bot command is just "summon", in today's update we've added a config to make it available for non-gm accounts again

**Comment by BloodRunsCold** [comment]
Sorry celguar, I meant summon, I had it in a macro for a long time and forgot that there was no . in front of it. It used to summon the bots to me immediately regardless of where they were, that's what I would like to have again. Sorry for the confusion.

**Comment by BloodRunsCold** [comment]
Ah, I see now that the whole thing was updated! Found the option to enable the summon command again, thanks. Also really love the option to speed up bot login without changing anything else.
