### ISSUE TITLE
The server download website cannot be connected

### ISSUE THREAD

**Issue by stephenmarquis** [celguar/mangosbot-bots#222]
First of all, thank you for your maintenance and sharing of the project. This is the best server I have ever experienced

Recently, I downloaded the project again, and there was a problem that couldn't be downloaded

Feedback to you: vanilla, tbc, and wlk server download websites（ http://ashamanecore.com ）"Unable to connect normally, the following prompt will appear:"

The vanilla module not found

Starting download in 10 seconds...

Repeatedly, if you directly use the downloader by copying the download address, it will also cause you to fail to download.

Could you provide an alternate download address.

Looking forward to your answer

![1](https://user-images.githubusercontent.com/450979/227792566-bc877b0a-c084-4f4b-8ee2-374fe921e0df.png)

**Comment by celguar** [comment]
https://mega.nz/folder/mRk3DCoZ#2nkNx9NlayG0Lj9Un8dsYA

**Comment by stephenmarquis** [comment]
> https://mega.nz/folder/mRk3DCoZ#2nkNx9NlayG0Lj9Un8dsYA

Thank you, download and run successfully
