### ISSUE TITLE
not able to install any module.

### ISSUE THREAD

**Issue by Naylz** [celguar/mangosbot-bots#224]
stuck in an endless loop whenever I try to download the modules.
it says:

Downloading Vanilla module...(~750 MB)

and after a few minutes it says:

The vanilla module not found
Starting download in 10 seconds...

Tried deleting complete SPP folder and reinstall everything, still not working.

**Comment by Stas724** [comment]
On the same exact boat. Been like this for a few days now. I was just about to post a poll and saw you did. @celguar can you fix this?

**Comment by celguar** [comment]
I'm sorry guys the host is probably down.
Use this 
https://mega.nz/folder/mRk3DCoZ#2nkNx9NlayG0Lj9Un8dsYA
Put archive to SPP_Server/Modules
