### ISSUE TITLE
Burning Crusade Expansion Account Data Error?

### ISSUE THREAD

**Issue by Naylz** [celguar/mangosbot-bots#227]
When I try to login into tbc I get following error message in client:

_Your account is authorized for the Burning Crusade expansion, but the computer you are playing on does not contain Burning Crusade data. To play on this machine with this account, you must install the Burning Crusade. Additional data is available at: [www.worldofwacraft.com/burningcrusade/download](http://www.worldofwacraft.com/burningcrusade/download)_

**Comment by Slotease** [comment]
Yeah, i am getting this as well. I thought it was a botched install, account not authorized to use the enxpansion inside of cmangos itself so set it to account set addon 1 or whatever it was, write protected wtf file that kept reverting back to initial non 127.0.0.1 ip.

None of that. All info is correct. I played the vanilla with bots and it was alright albeit with terrible frame rates. It stuttered from 50-60 all the time on a gtx 3060 12gb no matter what setting i used in the graphic section. I could set it low and it would be the same FPS as a setting of high.

So when i tried to play TBC to see if i got better fps i got this error.

**Comment by celguar** [comment]
if you are using tbc client from wowdl.net, their client is incomplete and is missing TBC expansion data. That's why you get this error

**Comment by celguar** [comment]
as for stutters you can try vanillafixes
https://github.com/hannesmann/vanillafixes

**Comment by Slotease** [comment]
> as for stutters you can try vanillafixes https://github.com/hannesmann/vanillafixes

I was indeed using that client from wowdl.net. Good catch. Is it a  2.4.3.8606 i am after?

I will try the vanilla fixes and report. So far so good with the experience. I got vanilla to work and i got wotlk to work. Cool project
