### ISSUE TITLE
Compiling Error: TBC and Classic

### ISSUE THREAD

**Issue by fatalieror** [celguar/mangosbot-bots#249]
Hey,

after a fresh clone i receive the following errors in TBC and Classic: 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2681	'Action *': invalid expression type for dynamic_cast	Bots	C:\Users\AL\Desktop\20220401\20230414\mangos-classic\src\modules\Bots\playerbot\strategy\generic\DungeonMultipliers.cpp	Line 11	
Error	C2872	'Action': ambiguous symbol	Bots	C:\Users\AL\Desktop\20220401\20230414\mangos-classic\src\modules\Bots\playerbot\strategy\generic\DungeonMultipliers.cpp	Line 9	
Error	C2511	'float ai::PreventMoveAwayFromCreatureOnReachToCastMultiplier::GetValue(Action *)': overloaded member function not found in 'ai::PreventMoveAwayFromCreatureOnReachToCastMultiplier'	Bots	C:\Users\AL\Desktop\20220401\20230414\mangos-classic\src\modules\Bots\playerbot\strategy\generic\DungeonMultipliers.cpp	Line 10

**Comment by kadeshar** [comment]
Provide cmake, boost and visual studio version.
Which options you checked in cmake?

**Comment by fatalieror** [comment]
Cmake 3.20.2
boost: 1_69_0
Visual Studio 2017

Ike3: https://github.com/celguar/mangosbot-bots
Mangos: https://github.com/celguar/mangos-classic/tree/ike3-bots

BUILD_GAME_SERVER
BUILD_IKE3_BOTS
BUILD_LOGIN_SERVER
BUILD_SCRIPTDEV

**Comment by kadeshar** [comment]
Try this options and RelWithDebInfo configuration
![obraz](https://user-images.githubusercontent.com/28183654/232378915-7c748c54-c5c3-4372-b873-dfdc9f6e2d00.png)

**Comment by fatalieror** [comment]
Tried as described with RelWithDebInfo.

![image](https://user-images.githubusercontent.com/1300834/232601887-46c4ff46-cc7c-4e49-bd8c-0f4ce70e10fe.png)

**Comment by kadeshar** [comment]
Try rebuild not build (worked for me).

**Comment by fatalieror** [comment]
So you had the same Problem?

I tried everything. Delete Cache. Rebuild. Re-clone all Repo's.
I dont know what else i could do.

**Comment by celguar** [comment]
I'm not sure cmangos supports visual studio 2017 anymore. Did you try stock cmangos? I did try 2017 last year and it didn't work for me

**Comment by celguar** [comment]
Or maybe we added code that only works in later versions of Visual Studio...Can you try with latest code please?

**Comment by fatalieror** [comment]
Changed to VS2019. Works now. Cheers.
