### ISSUE TITLE
After updating my server, several mmap erros

### ISSUE THREAD

**Issue by Aishade12** [celguar/mangosbot-bots#270]
![Screenshot 2023-06-12 162336](https://github.com/celguar/mangosbot-bots/assets/136213074/86e3a742-e5f5-4f8a-8883-8a3dfb50bddc)

**Comment by nicolasbocquet** [comment]
Got the same here : https://github.com/celguar/spp-classics-cmangos/issues/170

**Comment by nicolasbocquet** [comment]
Thanks for your answer, @celguar !
