### ISSUE TITLE
Socket::OnError

### ISSUE THREAD

**Issue by Purple-23** [celguar/mangosbot-bots#274]
Whenever the server has been running a little while and I happen to be in either westfall or stormwind, occasionally the CLIENT will crash, not the server, and I will get this error:

Socket::OnError.  An existing connection was forcibly closed by the remote host.  Connection closed.

The server is consistently running even after my client crashes.

What is this and how can I fix it?

Edit:  The wowerror that comes up states:

wowerror not enough memory resources are available to process this command.

But the server still runs and I can relog in just fine.  I am updated and running the latest BETA build.  There are no error logs.

**Comment by celguar** [comment]
Where do you see this error? How much ram free you have when it happens?

**Comment by Purple-23** [comment]
I actually solved this issue by installing and applying [https://www.techpowerup.com/forums/threads/large-address-aware.112556/]
