### ISSUE TITLE
Update to Cmangos-TBC

### ISSUE THREAD

**Issue by d3athbl0w** [celguar/mangosbot-bots#28]
Could it be updated for Cmangos-TBC?

**Comment by celguar** [comment]
Sure, I will make a fork of cmangos-tbc with it. Stay tuned

**Comment by celguar** [comment]
> Could it be updated for Cmangos-TBC?

Sure, I will make a fork of cmangos-tbc with it

**Comment by cocely** [comment]
cmangos-tbc random robots cannot use spells，
Where do I need to set what

**Comment by celguar** [comment]
> cmangos-tbc random robots cannot use spells，
> Where do I need to set what

Hello! Can you give more details? What is your source for cmangos-tbc + bots?

**Comment by cocely** [comment]
patch form https://github.com/celguar/mangos-tbc
Use your merged patch to upgrade to cmangos-tbc to the latest version
core https://github.com/cmangos/mangos-tbc/ latest version
bots https://github.com/celguar/mangosbot-bots
random robots cannot use spells

**Comment by celguar** [comment]
@cocely My old tbc repo was not correct anymore. I will rework core patch in new fork of cmangos-tbc, stay tuned

**Comment by celguar** [comment]
Updated to support CMaNGOS TBC
