### ISSUE TITLE
Error loading Relations [Cmangos/TBC]

### ISSUE THREAD

**Issue by d3athbl0w** [celguar/mangosbot-bots#29]
Thanks for your work adapting this to cmangos <3

![Captura](https://user-images.githubusercontent.com/14060040/106233331-a4245800-61cc-11eb-9c64-a98cd8452102.PNG)

**Comment by celguar** [comment]
Sure. Though it's not yet ready. I had a crash in tbc yesterday soon after it stsrted. I'll try to fix it

**Comment by celguar** [comment]
Fixed in https://github.com/celguar/mangosbot-bots/commit/fe3ef86cc8a21e54050f1f1632a2c9979fedf95c
