### ISSUE TITLE
Error Compiling Cmangos-TBC with last rev

### ISSUE THREAD

**Issue by d3athbl0w** [celguar/mangosbot-bots#30]
![image](https://user-images.githubusercontent.com/14060040/107784318-abe21180-6d21-11eb-9c90-23b9a182f83e.png)

**Comment by celguar** [comment]
Each cmangos fork has ike3 bots submodule with last compatible version. Main bots repo is developed using all 3 cores, so it may take some time to adapt new changes if they were made using 1 core and cause errors in other 2.
E.g. we added LFG support for bots. But it only works in wotlk core and no fix for pre-wotlk cores has been added yet. So pulling latest bots code is not the best idea sometimes. I try to make it compatible asap, but sometimes it means a day or two. :)

**Comment by celguar** [comment]
Fixed in https://github.com/celguar/mangosbot-bots/commit/695db77752caa1d03131686805398134d92aeba6
