### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by cocely** [celguar/mangosbot-bots#31]
[eb5366324a3d323dd263052240e5d51027f08f7d_mangosd.exe_[21-2_16-27-32].txt](https://github.com/celguar/mangosbot-bots/files/6021772/eb5366324a3d323dd263052240e5d51027f08f7d_mangosd.exe_.21-2_16-27-32.txt)

**Comment by celguar** [comment]
@cocely  Hello! Thanks for report! We'll check
