### ISSUE TITLE
[AI Logic] Group Bots follow player when he's dead/ghost

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#32]
**Description:**

When you die and go the graveyard the bots will teleport to you at the Spirit Healer. Once you start moving towards your corpse to revive yourself, the bots will follow you at matching speed through the world. This causes them to pull aggro of anything in their path. This can either lead to their deaths or to pull all the mobs nearby you when you revive.

**Expected behaviour:**

When you're dead, the bots should wait where they are. If they die themselves then they should wait at the Spirit Healer.

**Steps to reproduce the problem:**

1) Die
2) Wait for a moment for bots to teleport to you at the graveyard
2.a) If the bots are in combat they will have to finish combat before teleporting to you
3) Run to your corpse

**Solution:**

When master is a ghost give the bots **nc +stay**. 
Optionally, give bots **nc +follow** once the master is back alive.

```
if UnitIsGhost("player") and dead ~= 1 then
	nc +stay
	dead = 1
end
if not UnitIsGhost("player") and dead == 1 then
	nc +follow
	dead = 0
end
```

**Comment by celguar** [comment]
Fixed in https://github.com/celguar/mangosbot-bots/commit/490a4889c0d69af9f44b84fd80a1c629905d1578
