### ISSUE TITLE
[AI Strategies] Group Bots seek targets on their own,  outside the group, without permission

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#33]
**Description:**

There are 3 strategies for target seeking: **+dps assist**, **+tank aoe**, **+pvp**
These strategies help bots determine which targets to attack in the following way:

a) **+dps assist** : go after the target with the highest threat held by someone else
b) **+tank aoe** : keep the highest threat on all enemies engaged in combat (or at least it should)
c) **+pvp** : prioritize enemy faction players/bots

Normally, +dps assist and +tank aoe only take into account the threat inside the party they're in, but currently they take into account everything going on around them, and they try to help players who are fighting outside of the group.

Bots inside human player groups with +pvp drop everything else and prioritize targeting enemy players.

**Expected behaviour:**

Group bots with +dps assist or +tank aoe should only seek targets that threaten the group internally, anyone else from outside the party should be ignored unless explicitly told to attack. 

Bots who become part of a group with a human player controlling them, should automatically be taken away the nc -pvp strategy. This strategy is only useful for randombots so they can engage other players/bots in pvp. 

The problem with how these strategies work right now is that it takes away the control of the bots from the human players, leading to chaos, where the bots inside the party seem to have a mind of their own. While it is ok for randombots to try and help or attack other players/bots on their own, the human player should always be able to decide whom to attack. 

**Steps to reproduce the problem:**

1) Have any of the 3 strategies applied to bots in your party: **nc+dps assist,+tank aoe,+pvp**
2) Be around other bots who are fighting, or around enemy players (in case of **+pvp**)

**Solution:**

For +dps assist and +tank aoe: 
Limit the target seeking only to those who are engaged in combat with members of the bot's own group, unless solo.
For +pvp:
This should be the default strategy for bots, but the moment they are in group with a human player this should be removed, nc -pvp.

**Comment by celguar** [comment]
@leontedragos Fixed.
They no longer help other bots, unless you attack the mob creating threat. Then this mob becomes a possible target for group bots, even if tagged by another player/bot.
