### ISSUE TITLE
[AI Pathing] Group Bots teleport and fly through terrain

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#34]
**Description:**

Group bots who are at a distance from the player, if being told to follow, will teleport to the player and immediately after, they will fly through terrain back those the targets they were attacking before they were given the follow command. Even when out of combat, the distance they prefer to use teleport instead of walking is far too short.

**Expected behaviour:**

The bots should try and run back to the player instead of teleporting, unless they are very far away (maybe >100 yards, outside of the minimap borders). They should also walk and use proper pathing instead of flying straight through terrain.

**Steps to reproduce the problem:**

1) Ask your party bots to attack a target then move away from their location, the farther the better.
2) Issue a follow command either using the mangosbot addon shortcuts or by typing "follow" in party chat.

**Solution:**

The best example I can give is Trickerer's NpcBots who have exemplary pathing (probably thanks for the core as well. In the majority of situations, even if you jump off a cliff, the bots will try to find the correct pathing to get to you. They will take the road that goes behind the cliff, run to you and CC everything in their way if they can (freeze, snare, fear, stuns, whatever they can). They will not fight any mobs unless you also attack their pursuers; they're just interested in running, evading and making their way to you. BUT, if you jump off a cliff and there's just no path leading down the cliff to get to you, they will jump off the cliff too.  And only when they are very far away, off the minimap, do they teleport. It's very elegant.

**Comment by celguar** [comment]
@leontedragos Fighting ike3 bots and Cliff jumping NPC Bots are 2 different situations. If you give example of NPC Bots, then tell me how do you stop NPC Bots from fighting mobs they fight and make come to you, ignoring them?

**Comment by leontedragos** [comment]
Well, I can't say for sure how exactly they work without looking at their source code, but distance and whether or not the player is attacking a certain target definitely play a part. 

For instance, if the bot is 50 yards away from the player and the longest spell range is 30 yards, then there's no point for the bot to fight anything. So he will do his best to reach the player. If he's attacked, he will use whatever instant CCs or heals to stay alive. Chances are the mob will lose aggro if he's cc-ed by the time the bot reaches the master anyway. 

You can, of course, give ike3's bots the command to flee, but that's the same slippery slope I've presented before. if the bots are passive, then they are not doing anything to protect themselves. They're not healing, using shields, defensive cooldowns or CC-ing. 

Ultimately, the point of the "FOLLOW" command is for the bots to join the master and follow him. The command isn't called "Do as you like", because that's how the bots are currently acting. I give them a follow command and they're just ignoring me, if they're fighting in combat, that is. 

What is objective of the bots if not to assist the master in combat? If so, who knows better who or what should be attacked? 

On V1 the bots will fight needlessly as you are running away and the best you can hope for is for you to get out of range and the bots to teleport to you. But that's a cop out, not an actual achievement. There are situations when you will be frustrated that they're not in teleport range and they're fighting/dying pointlessly. 

As for how they should do it, I don't know the specifics, but the follow command should override their base combat routines until their purpose has been met, i.e. you have reached the master's location.

**Comment by celguar** [comment]
Pathing has been improved, closing
