### ISSUE TITLE
[Feature Request] [Wotlk DB] Realmlist

### ISSUE THREAD

**Issue by Twiggstar** [celguar/mangosbot-bots#345]
Hello. I have made my server available to public. Externally it is possible to connect to it. But from the local machine (where the server is hosted) i can't connect. I found out the issue by comparing cores from another server.

This one is missing localAdress column in the realmlist table. Adding it manually doesn't solve the issue.
I hereby request a way to properly handle local connections or a way to solve this issue.

**Comment by celguar** [comment]
if your router supports loop back just use your external IP in realmlist.wtf
If not you can create a 2nd realm entry in realmlist table and change it IP to your LAN IP then you use that realm and others keep using the external one

**Comment by Twiggstar** [comment]
No it does not support loop back i have tried external IP. I will try creating a realm entry, thanks.
