### ISSUE TITLE
Player character stays logged in in world [ Vanilla - 1.12.1 ]

### ISSUE THREAD

**Issue by dripone** [celguar/mangosbot-bots#365]
Reproduce the problem with SPP-Classics:

1. Create a character
2. Log in with it and do a quest, then log out.
3. Create a new account, new character and log in to the world.
4. You can see that the character from step 1 and 2 is still logged in and stays in one place.

**Comment by celguar** [comment]
Did you alt F4 or use logout button to log off from character 1?

**Comment by dripone** [comment]
Normal logout.
