### ISSUE TITLE
Serve_Update.bat can't download all the files

### ISSUE THREAD

**Issue by Qu1ProQu0** [celguar/mangosbot-bots#370]
I wanted to try this offline experence. Unfortunatelly, Server_Update.bat during installation when he reach "Receiving objects" downloading stops at max 2% and I get the error that "System can't find specffic path". I've put installer at my SSD drive but error continues.
![error](https://github.com/celguar/mangosbot-bots/assets/173637781/caeec0fc-fe36-4ac9-b1c3-e794cb8a1121)

**Comment by celguar** [comment]
Hello, make sure path to repack has no non-latin characters like ćàē etc

**Comment by Qu1ProQu0** [comment]
> Hello, make sure path to repack has no non-latin characters like ćàē etc

Ok, apparenty I shouldn't use VPN while downloading. Everything works.
