### ISSUE TITLE
cannot start worldserver anymore after latest updates!Why does the program suddenly not support Windows 2016?

### ISSUE THREAD

**Issue by kangyongwen** [celguar/mangosbot-bots#372]
Why does the program suddenly not support Windows 2016?windows 10 is goog!
<img width="665" alt="微信图片_20240714014453" src="https://github.com/user-attachments/assets/5ae0b550-4517-43ea-be61-5fb36ce7b477">

**Comment by celguar** [comment]
Can you please translate what it says

**Comment by Mr-Noob-ody** [comment]
My mangosd..exe closes immediately. Tried tbc and wotlk. An error text is seen in the launcher window, yet refreshes a little to fast for me to post.

**Comment by celguar** [comment]
Hello try install latest vcredist from Microsoft website

**Comment by Mr-Noob-ody** [comment]
Installed latest vcredist and Mangosd.exe now running.
