### ISSUE TITLE
[AI Logic] Healers casting revival spells twice

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#41]
**Description:**

Healers cast revival spells twice, back to back. This causes them to waste mana, be locked into a secondary useless action for the duration of the second cast and just generally waste time. 

**Expected behavior:**

They should wait a couple of seconds after their first cast to check if the target still needs to be revived. 

**Steps to reproduce the problem:**

1. Have someone in your party die
2. This bug occurs with both paladins, priests and druids, so you need any of those

**Solution:**

Some logic must stop them from casting it more than twice, so I imagine that adding a cooldown period between casts might solve this issue.

**Comment by celguar** [comment]
Fixed in update
https://github.com/celguar/mangosbot-bots/commit/7e9ae0e679d8138f7fd184939dbd2d9716c6e871
