### ISSUE TITLE
[Crash] Mage Auto Talents can cause server crash

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#43]
**Description:**

I've been experimenting with custom talents. I managed to setup successfully talents for paladin, rogue and priest, but for my mage they either don't apply at all, or they crash the server upon mage level up.

# Mage
AiPlayerbot.PremadeSpecName.8.0 = Universal Mage
AiPlayerbot.PremadeSpecProb.8.0 = 100
AiPlayerbot.PremadeSpecLink.8.0.25 = 2552552312231531

This is what I used to crash the server. This basically puts all the points in arcane tree if you play with 3x talents by level 25. 
There's an error in the console that shows up even for some of the premade specs, the same message. It could be connected.
https://imgur.com/ehDsRlb

**Comment by celguar** [comment]
@leontedragos  Fixed in update
https://github.com/celguar/mangosbot-bots/commit/e5a11a9e12a8c6c66e1618761af8c878edc47af1
