### ISSUE TITLE
AI healing(priest bot) don't want to heal "player"

### ISSUE THREAD

**Issue by misialos** [celguar/mangosbot-bots#44]
AIbot healing class priests after some time don't want to heal they ignore "player" in group, they just buff "player" and they just focus other "bots" in group healing and keep ignoring even when "player" is tanking all mobs. Tested on 20+ priests bots and same thing they all ignore "player" if im alone with priestbot in group he just using "FADE" spell and spam shadow word plain or wand attack

Tried to change strategies/resetai and nothing helps even got mangosbot addon to easier changing things still same thing

playing right now VANILLA 1.12.1 SPP collection founded here https://spp-forum.de/viewtopic.php?f=4&t=373

**Comment by misialos** [comment]
edit1
I have no idea how to update mangos bots, i supposed download new code and just put it in SPP server folder? can some1 explain me 'how to'? or just run "Server_Update" file is enough?

**Comment by misialos** [comment]
FIXED you can delete this i just REinstalled everything and it fixed my problem

**Comment by celguar** [comment]
Closed by request
