### ISSUE TITLE
[Request] Hunter out of ammo notification

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#45]
**Description:**

Unless you type "stats" regularly, chances are your hunter has run out of ammo and you don't even know it! 
I would like a QoL feature for the hunters to say in chat when they're out of ammo for their ranged out. I can be like one of those red text errors "can't flee" or something.

**Comment by celguar** [comment]
Added in https://github.com/celguar/mangosbot-bots/commit/f71204a2809b85791a355ebd457c061dcd9c6ce9
