### ISSUE TITLE
Min and Max level for bots

### ISSUE THREAD

**Issue by misialos** [celguar/mangosbot-bots#46]
Hey this option in aiplayerbot.conf in vanilla doesn't work whenever i have bots in game new or old most of them are lvl 1 no matter what i do or change,i just got spammed with lvl 1 bots. 

this is my confing and still lvl 60 are 5-10 bots, lvl 1 bots are 774 and some around 20-40
AiPlayerbot.RandomBotMinLevel = 55
AiPlayerbot.RandomBotMaxLevel = 60

**Comment by celguar** [comment]
@misialos Fixed in update
https://github.com/celguar/mangosbot-bots/commit/3d8400f0eee4ecd0e1a6c62bce0dd608877cce18
