### ISSUE TITLE
Bugs bots 1-7 lvl, crash server

### ISSUE THREAD

**Issue by Timesaiver** [celguar/mangosbot-bots#47]
So, what I got, I made it so that the bots increased their level with the help of mobs and quests, all from level 1, the configuration is almost untouched, the bots are 200-1000, the server x10 settings are minimal. Bottom line: we start all right, the bots come in, everything stops at reaching level 5-7, a lot of level 1 bots. Of the 100% bots, 87-95% are level 1-7, at least they leave the starting location from level 8-19 and everything also stops, there is no progress. The server worked for a maximum of 2-3 hours, red lines in cmd world, errors of achievements, I understand that the bots can not get them, errors of abilities, the server crashes, you need an auto-restart for this case. I will continue to test, let's see, I would like to see the transmogrifier, master portal, auto-login, I am still 19 lvl, before that everything in the world is normal in terms of settlement and quests. If that sorry for language, I Russian all Hi! 😅

**Comment by celguar** [comment]
@Timesaiver Привет, напиши пожалуйста в дискорд, или на форуме 👍

**Comment by celguar** [comment]
Their random levels will be fixed in next update

**Comment by Timesaiver** [comment]
> Их случайные уровни будут исправлены в следующем обновлении

Spp-forum? hello ^^

**Comment by celguar** [comment]
@Timesaiver Можешь в дискорде меня найти, ник такой же :)

**Comment by celguar** [comment]
Random levels fixed
