### ISSUE TITLE
[Request] Strategies saved permanently for alt bots

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#48]
One of the biggest annoyances of playing with the bots for a prolonged period of time is having to redo their strategies so often.

I request a feature to definitively save the strategies for the bots in my party. These strategies should not be reset under any circumstances unless I explicitly do it myself using "reset ai". Or, have the option to save them somewhere externally, so that whenever they are reset I can just reload their saved strategies. 

I could, of course, create macros for each individual bot, but the average player may not know how to do this, or be experienced/comfortable enough to add/remove strategies that often.

**Comment by celguar** [comment]
@leontedragos How do you reset them then? They are reset either by doing "reset ai" or by doing "Reset Bots" from launcher

**Comment by leontedragos** [comment]
I did not track all the ways in which they reset, but apart from me doing reset bots a lot for testing, sometimes they reset for other reasons. Such as switching to my alts (possibly), or updating the server (possibly). Either way, I've always found myself redoing strategies a lot.

**Comment by leontedragos** [comment]
I just logged in on my alts to assign their talents and after logging back on my main their strategies were reset, eh... not good.

**Comment by leontedragos** [comment]
I did a server restart and strategies reset again. I had the bots disconnect and connect, I had myself logout, I used save all. And still they reset.

**Comment by leontedragos** [comment]
I figured out what the issue is. 
If you tell the bots to "leave" in guild chat in order to disband the group BEFORE logging out or restarting the server, it causes the bots to reset their talents.
But, if you're still in the party when you logout or restart and AFTER you tell them to "leave" to disband their party and reinvite them, then their strategies are still saved.

**Comment by celguar** [comment]
Fixed https://github.com/celguar/mangosbot-bots/commit/06f43d5cb79cf78b4b19d5b62c2801794aa9e06b
