### ISSUE TITLE
[Crash] Adding bots from a different account causes instant server crash

### ISSUE THREAD

**Issue by leontedragos** [celguar/mangosbot-bots#50]
This issue is present from V1, but it's still relevant. 
If you try to .bot add a bot from a different account than your current one, assuming that your current account is non GM, then the server will crash immediately. 
Last time we talked about this, you said that this is to prevent normal accounts belonging to people causing harm to other people's accounts. That's fine, but the simple act of trying to add a bot from a different account shouldn't crash the server. It should throw some kind of error back at the user saying "not possible", instead.

Furthermore, it would be beneficial if there was a config allowing / denying access to bots from other accounts. On my own singleplayer server, I don't need to be concerned with this security measure. I would like to be able to invite bots using my non GM account from other accounts.

**Comment by celguar** [comment]
Fixed 15d9f881683ec9a680a641a79d919d239047af88
