### ISSUE TITLE
Shadowmourne and Raise Dead Bugged

### ISSUE THREAD

**Issue by revan225** [celguar/mangosbot-bots#52]
For the WotLK section of SPP Classics I have found two bugs. I apologize if this is the wrong area but this is where it links to on the forum to post any discovered bugs.

Shadowmourne's special ability does not work. Soul shards do not gather in any capacity; further, it will start to play the initial animation of gathering souls, however since there are no soul shards to generate or dissipate the effect remains until logging out.

Raise Dead does not work in any capacity. Tried running server on two different computers and tried repairing the install but raise dead will never cast. It will turn dark as if it was cast, and when clicked on again will state "spell is not ready". This also remains until logging out.

**Comment by celguar** [comment]
Sadly no ppl to work on spell bugs atm. Raise dead reportedly was fixed by core devs (cmangos).
