### ISSUE TITLE
Shadowfang issue

### ISSUE THREAD

**Issue by Littlelucy99** [celguar/mangosbot-bots#53]
Hey, i wanted to REPORT  an breaking bug what occures all the time with the dungeon  Shadowfang keep on 3.3.5a, if you kill the boss, it's crashing the server.. sometimes it works on the second try, and sometimes it's not working anymore and the server keeps closing after kill, i know it might be not a game breaking bug, but still if you run dungeons LFG or random it's bad when the server crashes :) but all in one again, thanks for this great repack - Yeah im playing on 1x blizzlike rates, and testing the dungeons.

Ofcourse only if you didn't fix this bug yet with the crash in the new updates.

**Comment by celguar** [comment]
@Littlelucy99 Hello and thanks for your report! 👍🏼 
Since this repo is for bots, I require addition information about your issue:
- Repack version
- What boss has the issue
Please provide this info and we'll look into this
Thanks in advance

**Comment by Littlelucy99** [comment]
- Repack version its 3.3.5a (WotLK)
- Boss who has the issue -  Archmage Arugal
- Issue - When you hit Archmage Arugal down to 0 LIFE/HP the server is crashing.

**Comment by Littlelucy99** [comment]
- Boss - Bazil Thredd
- Dungeon - Stockades
- Same issues happens here, server is crashing when he hits 0 HP.

Might be more Classic dungeons are buggy? what is about the endgame dungeon / raids they are working ?

**Comment by celguar** [comment]
@Littlelucy99 Probably LFG system causes it when you kill last boss and should get a reward. Thanks for the info, I'll check it soon

**Comment by Littlelucy99** [comment]
Yeah i have been looking forward what causes this problem after i see never any reward .. it might be that problem? i used to check the database i couldn't find really something wrong.

**Comment by celguar** [comment]
LFG crash fixed
