### ISSUE TITLE
Install not work

### ISSUE THREAD

**Issue by DeadDreams86** [celguar/mangosbot-bots#56]
Hi! Thanks a lot for you work. 
i tried to install SSP but **ftp://161.97.113.128:9876/spp_classics_data/vanilla.7z** not work.

**Comment by celguar** [comment]
> Hi! Thanks a lot for you work. 
> i tried to install SSP but **ftp://161.97.113.128:9876/spp_classics_data/vanilla.7z** not work.
> 

@DeadDreams86 Hello! spp classics mangos is discontinued and can't be installed. Use SPP_Classics_V2.exe from spp-classics-cmangos repository
