### ISSUE TITLE
Pets dont scale stats

### ISSUE THREAD

**Issue by KingLich1** [celguar/mangosbot-bots#58]
I was testing out with warlock pet Imp, it had way too low mana and health, also its regeneration was really low.
This issue might exist in other pets, especially hunters.

Also, I think imps should be able to melee, but they can't.

**Comment by celguar** [comment]
@KingLich1 Hello, it's no problem. Though I'm not sure me or Cmangos devs can do anything with information like "way too low mana and health" :) What expansion, what is your level, what buffs you do you have, what are your stats? Why you think it's too low mana and health? Did you comapare with retail servers? It needs more information than this to even start thinking about fixing it

**Comment by celguar** [comment]
There are hundreds of fixes in cmangos official channel now, I'll try to fetch them next week and you will be able to check again, maybe it will be fixed :)

**Comment by KingLich1** [comment]
tbc 2.4.3 version.  i was just 4-5 level and just received imp pet. When I look at the pet's stats and mouseover to the intelligence, for example it says "increases mana by 114" however, the pet's mana is 24. Same idea with stamina and spirit, it takes a minute to regenerate that 24 mana. Either the mouse over tooltip is wrong or the stats don't function, here.
