### ISSUE TITLE
Bot stuck at innkeeper when presumably trying to buy

### ISSUE THREAD

**Issue by Boxhead78** [celguar/mangosbot-bots#60]
Bots get stuck and spam emotes mostly inside of an inn.

Reverting the following commit fixes the issue for me: [Bot buy fix: Allow bots to buy specific items (such as a tabard) without a master.](https://github.com/celguar/mangosbot-bots/commit/68e2505e400fd0fc47999c0ee1cb792152255fdd)

Tested with wotlk servers.

**Comment by celguar** [comment]
Fixed 171b7b77597a94e0c5bbfc4dc014354c97c4c57f
