### ISSUE TITLE
LOW CPU USAGE

### ISSUE THREAD

**Issue by Stas724** [celguar/mangosbot-bots#65]
Hey; so I am curious to find out how do I increase the CPU USAGE for the MANGOS SPP for WOTLK 3.3.5a client. |

Currently running the latest version of SPP_Server from GITHUB that you have provided. I have multiple machines at home using 10900K's with 5.2GHZ & 64GB DDR4 @3600 MHZ CL16 and I feel like with the config I have set I should have more CPU usage. I have used the # AI Playerbot Alone Activity AIPlayerbot.botActiveAlone = 100 

meaning 100 percent of the bots should be fully active which seems like they are? but only having 15 percent cpu usage. no matter if I increase the Playerbot from 500 to 5000 I still am only getting 10 - 15 percent cpu usage. 

any commands I can use to have my cpu usage set to 90 percent as this PC would be a 24/7 dedicated server. Thanks!

[https://ibb.co/3pFNNNV](url)

**Comment by celguar** [comment]
@Stas724 Hello, try increasing MapUpdateThreads in mangosd.conf. Default is 3, make it CPU threads - 1.
I think it's unlikely that server will use your CPU fully, so I'm not sure why you want it to use more CPU, you get money for spent electicity or smth? :D

**Comment by celguar** [comment]
Sadly server is not coded to separate all its processes into many many threads, so it won't be able to fully use your CPU, but that MapUpdateThread config should give it a bit more power

**Comment by celguar** [comment]
@Stas724 Actually in next update we will lower CPU usage as we will make less computations for bots far away from real players. This will allow to have more bots and less lags if there are not very many real players in all parts of the world.

**Comment by Stas724** [comment]
@celguar Gotcha, now I understand. (: I appreciate you for explaining all this to me.

**Comment by DrumNoVoice** [comment]
Hello everyone, just did cpu threads -1 and when server was launching I saw an error, smth like "cpu threads can not be negative". Am I doing smth wrong? Or it need to be written like "- 1" with space?

**Comment by celguar** [comment]
Hello threads number should be a positive value

**Comment by DrumNoVoice** [comment]
> Hello threads number should be a positive value

hmm, so, as I can understand, if I write 1, the cpu usage will be better? :D

**Comment by celguar** [comment]
> > Hello threads number should be a positive value
> 
> hmm, so, as I can understand, if I write 1, the cpu usage will be better? :D

I don't know what do you mean by cpu usage

**Comment by celguar** [comment]
you can read whol conversation for details

**Comment by celguar** [comment]
make it CPU threads - 1 means CPU threads number - 1

**Comment by celguar** [comment]
No more significant improvements to multi threading are planned soon. Closing
