### ISSUE TITLE
bots and mounts

### ISSUE THREAD

**Issue by firelook** [celguar/mangosbot-bots#72]
With a group of 3 humans (non bots) and invite 2 bots to have a group of 5
=> everything is working fine to do quests.
=> BUT if you use mounts (ground of fly) no bots mount their own (can be on different levels)

**Comment by celguar** [comment]
> With a group of 3 humans (non bots) and invite 2 bots to have a group of 5 => everything is working fine to do quests. => BUT if you use mounts (ground of fly) no bots mount their own (can be on different levels)

Thanks for report, This will be fixed in next repack update

**Comment by celguar** [comment]
Should be fixed, let me know if it happens again
