### ISSUE TITLE
Aborted Connetcion

### ISSUE THREAD

**Issue by Derkon90** [celguar/mangosbot-bots#74]
I am totally noob to be honest, but this repack is very cool stuff and very realistic!! The problem is that sometimes (sometimes even few seconds after the restart) the server crashes and on the "Server Data Base" is showed some message like "Aborted connection 1 to db: 'db' user: Woltkcharacter' host: 'hostname' (Got an error reading communication packets) and some like that..... and i have to restart all....

**Comment by celguar** [comment]
@Derkon90 Hello, don't look at Database, it has no information about server operations. In latest update I made bots auto queue BGs, this increased activity causes crashes. I'm working on a solution. Until I fix it, please disable BG Bots in config

**Comment by Maravenerea** [comment]
Hello, I am having the same issue as user Derkon90:
"[Note] Aborted connection 37 to db: 'wotlkrealmd' user: 'root' host: 'localhost' (Got an error reading communication packets)"
(Several of these messages).

I have disabled BG Bots in SPP_Server -> Settings -> [expansion] -> aiplayerbot.conf. 
What I did was "# Enable BG/Arena for random Bots
AiPlayerbot.RandomBotJoinBG = 0". 
I am not sure if that was the right action to take, please correct me if I was wrong. In any case the issue persists, perhaps there is another solution?

Server is amazing, btw!

**Comment by slerick** [comment]
Hi! Im having the same problem as @Maravenerea and i cannot get my server to start.

I've tried disabling BG bots in the same way but it hasnt fixed the problem. It still crashes on startup. Any update on what to do?
Thanks

**Comment by celguar** [comment]
Seems to be workin now

**Comment by Derkon90** [comment]
Thank you so much, you re very seroiuos and professional! I will give yoy
my feedback as soon as possible

Il Mar 15 Mar 2022, 22:10 celguar ***@***.***> ha scritto:

**Comment by celguar** [comment]
@Derkon90 server can still crash sometimes, and it's due abnormal bot activity. We are working constantly to improve stability
