### ISSUE TITLE
Show English locale in dialog

### ISSUE THREAD

**Issue by biancong1208** [celguar/mangosbot-bots#86]
![2022-02-28_193925](https://user-images.githubusercontent.com/93648230/155978162-5adf6e85-cfbc-4966-9b48-4beb76da6d8a.png)
As shown in the figure, when I just log in, it displays Chinese, but after changing the region, it becomes English. How can I make it always display Chinese? THX @celguar

**Comment by celguar** [comment]
This comes from server dbc. To fix it you need to extract dbc files from Chinese game and put it in server/Modules/expansion/dbc folder

**Comment by biancong1208** [comment]
OK,THX,Let me have a try

**Comment by biancong1208** [comment]
> This comes from server dbc. To fix it you need to extract dbc files from Chinese game and put it in server/Modules/expansion/dbc folder

Thanks a lot, the problem was solved after re-extracting the dbc file.
