### ISSUE TITLE
Dungeon Finder

### ISSUE THREAD

**Issue by DiabloGato47** [celguar/mangosbot-bots#90]
Dungeon finder seems like it isn't working, the green orb doesn't even show beside the map, and it won't let me requeue after queuing once. It says I joined in the chat box but it doesn't actually join. The "find queue" button basically gets stuck and I can't use it anymore.
When I join with a group, they never choose their class even when with the correct group. Settings are correct within the notes as well so I'm not sure what is happening. 
PVP & Arenas are working fine.

I tried downloading both the repack and WoW 3.3.5a files again and still having the same problem.

**Comment by celguar** [comment]
@DiabloGato47 Hello and thanks for report. I'll try to make it work soon

**Comment by DiabloGato47** [comment]
Okay sounds good, the server (3.3.5a) is running great that seems to be the only problem I found so far. I'll continue to mess around on it until the dungeon finder is fixed.
