### ISSUE TITLE
WoTLK - mangosd.conf PathFinder.NormalizeZ causes the server to crash

### ISSUE THREAD

**Issue by janissaire** [celguar/mangosbot-bots#94]
Setting the variable "PathFinder.NormalizeZ" to 1 in mangosd.conf causes mangosd.exe to close itself a few minutes after starting it. Setting it to 0, no problem. 
"PathFinder.OptimizePath" is set to 1 in both cases. Process priority is high or real-time. UseProcessors is 0, and the processor has four cores.  
Wrath of the Lich King, SPP Server version 2.1.6_15.02.22. 

Don't know if this is the right place to report this problem, I don't use ShitHub. 
Thanks a lot guys.

**Comment by admadm123** [comment]
thank you hope it works

**Comment by MRafStudio** [comment]
Installed as you said
janissaire still fell to server 0, but it's rather curious. Attached files.

![Error](https://user-images.githubusercontent.com/104055624/165289556-d2d4f779-2695-4b11-967f-43dc7ea8506a.png)
[wotlk.zip](https://github.com/celguar/mangosbot-bots/files/8562704/wotlk.zip)
[Crashes.zip](https://github.com/celguar/mangosbot-bots/files/8562728/Crashes.zip)
