### ISSUE TITLE
Can't start up Wotlk server. Help.

### ISSUE THREAD

**Issue by Xxmeu** [celguar/mangosbot-bots#98]
Please check out the Errors files.
[EventAIErrors.log](https://github.com/celguar/mangosbot-bots/files/8641835/EventAIErrors.log)
[Server.log](https://github.com/celguar/mangosbot-bots/files/8641837/Server.log)
[DBErrors.log](https://github.com/celguar/mangosbot-bots/files/8641872/DBErrors.log)

**Comment by celguar** [comment]
I need crash logs, server info - crash logs, only . txt files

**Comment by Xxmeu** [comment]
[69e2b7ef_mangosd.exe_[7-5_8-40-59].txt](https://github.com/celguar/mangosbot-bots/files/8644144/69e2b7ef_mangosd.exe_.7-5_8-40-59.txt)
Thanks for your reply. I've tried again and then realized that it could be started but took very long time to. Meanwhile, I created an acount and a character, but can't login to the game and then server crashed. Here's the crash logs.txt for checking.

**Comment by Xxmeu** [comment]
> I need crash logs, server info - crash logs, only . txt files

Thank you so much. I've tried again and then realized that it could be started but took very long time to. Meanwhile, I created an account and a character, but can't login to the game and then server crashed. Here's the crash logs.txt for checking.
[69e2b7ef_mangosd.exe_[7-5_8-40-59].txt](https://github.com/celguar/mangosbot-bots/files/8644163/69e2b7ef_mangosd.exe_.7-5_8-40-59.txt)
