### ISSUE TITLE
Regular crash due to Assertion Failure

### ISSUE THREAD

**Issue by alimalkhalifa** [celguar/mangosbot-bots#99]
Hey! Seems we have an assertion failure at

D:\MANGOS\cmangos\wotlk\src\game\Spells\Spell.cpp:419: Error: Assertion in Spell::Spell failed: caster != nullptr && info != nullptr

I was going to get in there and see if I can find a solution for it, but builds failed for me due to inability to find include files.

**Comment by celguar** [comment]
Hello. Crash log .txt files are in Crashes folder near mangosd.exe. You can upload it somewhere. ONLY .txt files

**Comment by alimalkhalifa** [comment]
Hey @celguar PFA

Thanks for looking into this

<script src="https://gist.github.com/alimalkhalifa/1fe1e3b57f5de9798b33b7c7a4f921bf.js"></script>

**Comment by celguar** [comment]
What is this .js file

**Comment by alimalkhalifa** [comment]
Apologies I am running a pretty gnarly seasonal flu :D copied the wrong link

https://gist.github.com/alimalkhalifa/1fe1e3b57f5de9798b33b7c7a4f921bf

**Comment by alimalkhalifa** [comment]
I have traced the call stack and found that Object::GetObjectGuid() was being called on a null Object, probably due to issues with cleaning up spells when a bot is removed/teleported/BG is completed

I am not sure of the base cause, additional investigation is required if this solution is undesireable
